### local variable
@base_url = http://localhost:3000/api/v1
# @base_url = https://capstone-5es2zkrl5a-et.a.run.app/api/v1

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImIzNjY1ZTc4LTU2MmItNGNkNC1iMTc5LTM4YWQ1OGJmYTA0MyIsInVzZXJuYW1lIjoiSm9obiBEb2UiLCJlbWFpbCI6ImpvaG5AZG9lLmNvbSIsImlhdCI6MTcwMjkwNDEyNSwiZXhwIjoxNzA1NDk2MTI1fQ.IDTw-moHLTiK434iklWXDNE32gRfEPI_UYYuG6VHkyE

### Sign up
POST {{ base_url }}/auth/register HTTP/1.1
Content-Type: application/json

{
  "username": "John Doe",
  "email": "john@doe.com",
  "password": "12345678"
}

### Sign in
POST {{ base_url }}/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "john@doe.com",
  "password": "12345678"
}


### Me
GET {{ base_url }}/auth/me HTTP/1.1
Authorization: Bearer {{ token }}
    
### Test prediction
GET {{base_url}}/predict/test HTTP/1.1

### Static content
GET http://localhost:3000/model/model.json HTTP/1.1